In [1]:
import pandas as pd
import numpy as np

In [2]:
meteor_showers = pd.read_csv('data/meteorshowers.csv')
moon_phases = pd.read_csv('data/moonphases.csv')
constellations = pd.read_csv('data/constellations.csv')
cities = pd.read_csv('data/cities.csv')

En el paso anterior lo que hacemos es cargar los datos de los csv provistos en formato csv, cada una con su nombre propio para que sean un dataframe separado cada uno.

In [3]:
cities.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 256 entries, 0 to 255
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   city      256 non-null    object 
 1   latitude  256 non-null    float64
 2   country   256 non-null    object 
dtypes: float64(1), object(2)
memory usage: 6.1+ KB


El método `.info()` lo que hace es buscar la información general del data frame, entregando detalles de cada una de las columnas y los valores no nulos que se encuentran dentro de ellas.

En este caso, se puede apreciar que las columnas:

`city` tiene 256 filas de valores no nulos, de tipo objeto.

`latitude` tiene 256 filas de valores no nulos de tipo decimal (float64)

`country` tiene 255 filas de valores no nulos de tipo objeto.

## Diferencias entre `info()` y `head()`

Principalmente, la diferencia, es que el método `head()` mostrará las primeras filas del data frame, mientras que `info` le dará un contexto a los datos contenidos en modo de resumen.

In [4]:
cities.head()

city  latitude               country
0    Abu Dhabi     24.47  United Arab Emirates
1        Abuja      9.07               Nigeria
2        Accra      5.55                 Ghana
3    Adamstown    -25.07      Pitcairn Islands
4  Addis Ababa      9.02              Ethiopia

In [5]:
meteor_showers.head()

name   radiant bestmonth startmonth  startday  endmonth  endday  \
0        Lyrids      Lyra     april      april        21     april      22   
1  Eta Aquarids  Aquarius       may      april        19       may      28   
2      Orionids     Orion   october    october         2  november       7   
3      Perseids   Perseus    august       july        14    august      24   
4       Leonids       Leo  november   november         6  november      30   

           hemisphere preferredhemisphere  
0            northern            northern  
1  northern, southern            southern  
2  northern, southern  northern, southern  
3            northern            northern  
4  northern, southern  northern, southern

# Información sobre los data frames 

Los data frames obtenidos de los csv tienen diferentes datos relevantes para la predicción de lluvias de meteoritos, tal como vimos en el caso del data frame `cities`, los otros casos tienen información sobre:

+ `constellations`: Las diferentes constelaciones y dónde pueden verse, la latitud donde se empiezan a ver y la latitud donde estas se pueden dejar de ver. En palabras sencillas, si estás en la Tierra, dependiendo de tu posición geográfica, podrás ver ciertas constelaciones, las cuales son específicas para ciertos meses en particular.

+ `moonphases`: Las fases de la luna, por ejemplo, el 2 de enero, había cuarto menguante (first quarter). O el 10 de enero hubo luna llena, el 24 de enero hubo luna nueva. Mientras que todas las fechas que hubo entre esas fechas en específico, implicaban el cambio de fase de la lluna.

+ `meteorshowers`: La información de lluvias de meteoritos. También muestra la información de la constelación de la cual proviene la lluvia de meteoritos. El mejor mes para verlo. El mes y el día desde cuándo será visible hasta el mes y el día en que podrá verse por última vez, el hemisferio en donde se presentará la posibilidad de visibilización y el mejor hemisferio de la tierra para verlo.

+ `cities`: Incluye la información de las ciudades, pero también su latitud y país al que permanecen.

# Consejo de manejar las fechas

Para manejar las fechas, lo mejor es transformar las fechas en números, debido a que computacionalmente cualquier lenguaje de programación podría ser indicador de un desorden, por ejemplo, computacionalmente, august (agosto) va antes que march (marzo). Entonces, el ordenar las fechas pasa a ser un proceso fundamental, especialmente en un data frame en donde tenemos las columnas día de inicio, mes de inicio, día final, mes final.